# Generated by Django 5.1.3 on 2024-12-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('score_processor', '0003_examsubjectconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScoreLines',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_id', models.CharField(max_length=50)),
                ('stream_type', models.CharField(choices=[('文科', '文科'), ('理科', '理科')], default='理科', help_text='文理分科(文科/理科)', max_length=10)),
                ('line_type', models.CharField(choices=[('C9层', 'C9层'), ('985层', '985层'), ('211层', '211层'), ('双一流层', '双一流层'), ('优分层', '优分层'), ('本科层', '本科层')], default='本科层', help_text='分数线类型:C9层，985层，211层，双一流层，优分层，本科层', max_length=20)),
                ('score', models.DecimalField(decimal_places=2, help_text='分数线值', max_digits=6)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '考试分数线',
                'verbose_name_plural': '考试分数线',
                'db_table': 'exam_score_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreDistributions',
            fields=[
                ('distribution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream_type', models.CharField(db_comment='文科/理科/统一', max_length=10)),
                ('level_type', models.CharField(db_comment='分析层级：city/district/school', max_length=20)),
                ('score_range', models.CharField(db_comment='分数段', max_length=20, null=True)),
                ('student_count', models.IntegerField(db_comment='学生数', null=True)),
                ('percentage', models.DecimalField(db_comment='占比', decimal_places=2, max_digits=5, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('cumulative_count', models.IntegerField(db_comment='累计人数', null=True)),
                ('cumulative_percentage', models.DecimalField(db_comment='累计百分比', decimal_places=2, max_digits=5, null=True)),
                ('density', models.DecimalField(db_comment='区间密度', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'score_distributions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreRankings',
            fields=[
                ('ranking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unified_student_id', models.CharField(db_comment='统一学生ID', max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('stream_type', models.CharField(db_comment='文科/理科/统一', max_length=10)),
                ('level_type', models.CharField(db_comment='分析层级：city/district/school', max_length=20)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('raw_score_rank', models.IntegerField(null=True)),
                ('total_count', models.IntegerField(db_comment='总人数', null=True)),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_score_threshold_flags', models.IntegerField(db_comment='总分达线标记(仅总分有效,位运算:1=本科线,2=特控线,4=211线,8=985线,16=清北线)', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '排名情况统计',
                'verbose_name_plural': '排名情况统计',
                'db_table': 'score_rankings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsExamIndicators',
            fields=[
                ('indicator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream_type', models.CharField(db_comment='文科/理科/统一', max_length=10)),
                ('level_type', models.CharField(db_comment='分析层级：city/district/school', max_length=20)),
                ('excellent_rate', models.DecimalField(db_comment='优秀率', decimal_places=2, max_digits=5, null=True)),
                ('pass_rate', models.DecimalField(db_comment='及格率', decimal_places=2, max_digits=5, null=True)),
                ('low_score_rate', models.DecimalField(db_comment='低分率', decimal_places=2, max_digits=5, null=True)),
                ('top_10_score', models.DecimalField(db_comment='前10名最低分', decimal_places=2, max_digits=6, null=True)),
                ('top_50_score', models.DecimalField(db_comment='前50名最低分', decimal_places=2, max_digits=6, null=True)),
                ('top_100_score', models.DecimalField(db_comment='前100名最低分', decimal_places=2, max_digits=6, null=True)),
                ('top_200_score', models.DecimalField(db_comment='前200名最低分', decimal_places=2, max_digits=6, null=True)),
                ('top_1250_score', models.DecimalField(db_comment='前1250名最低分', decimal_places=2, max_digits=6, null=True)),
                ('threshold_stats', models.JSONField(db_comment='各条线达线统计', null=True)),
                ('school_distribution', models.JSONField(db_comment='学校分布统计', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'statistics_exam_indicators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsExamTrend',
            fields=[
                ('trend_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream_type', models.CharField(db_comment='文科/理科/统一', max_length=10)),
                ('level_type', models.CharField(db_comment='分析层级：city/district/school', max_length=20)),
                ('mean_change', models.DecimalField(db_comment='平均分变化', decimal_places=2, max_digits=6, null=True)),
                ('mean_change_rate', models.DecimalField(db_comment='平均分变化率', decimal_places=2, max_digits=5, null=True)),
                ('std_dev_change', models.DecimalField(db_comment='标准差变化', decimal_places=2, max_digits=5, null=True)),
                ('score_segment_changes', models.JSONField(db_comment='分数段人数变化', null=True)),
                ('grade_changes', models.JSONField(db_comment='等级分布变化', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'statistics_exam_trend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatisticsPrecomputedMetrics',
            fields=[
                ('metric_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream_type', models.CharField(db_comment='文科/理科/统一', max_length=10)),
                ('level_type', models.CharField(db_comment='分析层级：city/district/school', max_length=20)),
                ('metric_type', models.CharField(db_comment='指标类型', max_length=50)),
                ('metric_value', models.DecimalField(db_comment='指标值', decimal_places=2, max_digits=10, null=True)),
                ('auxiliary_data', models.JSONField(db_comment='辅助数据', null=True)),
                ('last_computed', models.DateTimeField(db_comment='最后计算时间')),
                ('compute_duration', models.IntegerField(db_comment='计算耗时(秒)', null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'statistics_precomputed_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectStatistics',
            fields=[
                ('stat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stream_type', models.CharField(db_comment='文科/理科/统一', max_length=10)),
                ('level_type', models.CharField(db_comment='分析层级：city/district/school', max_length=20)),
                ('sample_size', models.IntegerField(db_comment='样本量', null=True)),
                ('mean', models.DecimalField(db_comment='原始分平均分', decimal_places=2, max_digits=6, null=True)),
                ('std_dev', models.DecimalField(db_comment='原始分标准差', decimal_places=2, max_digits=5, null=True)),
                ('median', models.DecimalField(db_comment='中位数', decimal_places=2, max_digits=6, null=True)),
                ('q1', models.DecimalField(db_comment='第一四分位数', decimal_places=2, max_digits=6, null=True)),
                ('q3', models.DecimalField(db_comment='第三四分位数', decimal_places=2, max_digits=6, null=True)),
                ('iqr', models.DecimalField(db_comment='四分位距', decimal_places=2, max_digits=6, null=True)),
                ('mode', models.DecimalField(db_comment='众数', decimal_places=2, max_digits=6, null=True)),
                ('skewness', models.DecimalField(db_comment='偏度', decimal_places=2, max_digits=5, null=True)),
                ('kurtosis', models.DecimalField(db_comment='峰度', decimal_places=2, max_digits=5, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subject_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectTScore',
            fields=[
                ('score_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unified_student_id', models.CharField(db_comment='统一学生ID', max_length=50)),
                ('stream_type', models.CharField(db_comment='文科/理科/统一', max_length=10)),
                ('level_type', models.CharField(db_comment='分析层级：city/district/school', max_length=20)),
                ('raw_score', models.DecimalField(db_comment='原始分', decimal_places=2, max_digits=6, null=True)),
                ('t_score', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('z_score', models.DecimalField(db_comment='Z分数', decimal_places=2, max_digits=5, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subject_t_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseExamConfig',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('score_processor.baseexamconfig',),
        ),
        migrations.CreateModel(
            name='BaseSchoolInfo',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('score_processor.baseschoolinfo',),
        ),
        migrations.CreateModel(
            name='BaseSubjectConfig',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('score_processor.basesubjectconfig',),
        ),
        migrations.CreateModel(
            name='ScoreStudentBasic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('score_processor.scorestudentbasic',),
        ),
    ]
