# Generated by Django 5.1.3 on 2024-12-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExamConfig',
            fields=[
                ('exam_id', models.CharField(db_comment='考试ID', max_length=50, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(db_comment='考试名称', max_length=100)),
                ('exam_date', models.DateField(db_comment='考试日期')),
                ('exam_type', models.CharField(blank=True, db_comment='考试类型：月考/期中/模拟等', max_length=20, null=True)),
                ('grade_level', models.CharField(blank=True, db_comment='年级', max_length=20, null=True)),
                ('semester', models.CharField(blank=True, db_comment='学期', max_length=20, null=True)),
                ('status', models.CharField(blank=True, db_comment='状态：active/inactive', max_length=10, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_exam_config',
                'db_table_comment': '考试基本信息表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseSchoolInfo',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('school_code', models.CharField(blank=True, max_length=20, null=True)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('school_type', models.CharField(blank=True, max_length=20, null=True)),
                ('school_level', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_school_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseSubjectConfig',
            fields=[
                ('subject_id', models.CharField(db_comment='科目ID', max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(db_comment='科目名称', max_length=50)),
                ('subject_type', models.CharField(blank=True, db_comment='科目类型：主科/副科', max_length=20, null=True)),
                ('full_score', models.IntegerField(db_comment='满分')),
                ('is_required', models.IntegerField(blank=True, db_comment='是否必修', null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'base_subject_config',
                'db_table_comment': '科目配置表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScoreStudentBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=50)),
                ('district_name', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('class_field', models.CharField(db_column='class', max_length=50)),
                ('select_type', models.CharField(db_comment='文科/理科/未确定', max_length=10)),
                ('chinese', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('math', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('english', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('physics', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chemistry', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biology', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('history', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('politics', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('geography', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'score_student_basic',
                'db_table_comment': '学生基础成绩表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_id', models.CharField(db_comment='统一考号(11位)', max_length=11)),
                ('exam_id', models.CharField(db_comment='考试ID', max_length=50)),
                ('original_student_id', models.CharField(db_comment='原始考号', max_length=50)),
                ('student_name', models.CharField(db_comment='学生姓名', max_length=50)),
                ('school_name', models.CharField(db_comment='学校名称', max_length=100)),
                ('class_name', models.CharField(db_comment='班级名称', max_length=50)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='exam_uploads/')),
                ('exam_id', models.CharField(max_length=50, verbose_name='考试ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('status', models.CharField(choices=[('PENDING', '等待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '成绩上传记录',
                'verbose_name_plural': '成绩上传记录',
                'db_table': 'exam_uploads',
                'ordering': ['-uploaded_at'],
                'managed': True,
            },
        ),
    ]
