# Generated by Django 5.1.3 on 2024-12-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseexamconfig',
            options={'managed': False, 'verbose_name': '考试基础信息设置', 'verbose_name_plural': '考试基础信息设置'},
        ),
        migrations.AlterModelOptions(
            name='examupload',
            options={'managed': False, 'ordering': ['-uploaded_at'], 'verbose_name': '成绩上传及记录处理', 'verbose_name_plural': '成绩上传及记录处理'},
        ),
        migrations.AlterModelOptions(
            name='scorestudentbasic',
            options={'managed': False, 'verbose_name': '学生基础成绩表', 'verbose_name_plural': '学生基础成绩表'},
        ),
        migrations.AlterModelOptions(
            name='studentmapping',
            options={'managed': False, 'verbose_name': '学号映射表', 'verbose_name_plural': '学号映射表'},
        ),
    ]
