# Generated by Django 5.1.3 on 2024-12-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_processor', '0002_alter_baseexamconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubjectConfig',
            fields=[
                ('config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_score', models.DecimalField(db_comment='满分', decimal_places=2, max_digits=5)),
                ('pass_score', models.DecimalField(db_comment='及格分数线', decimal_places=2, max_digits=5)),
                ('excellent_score', models.DecimalField(db_comment='优秀分数线', decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(db_comment='分数权重', decimal_places=2, default=1.0, max_digits=3)),
                ('mean_score', models.DecimalField(db_comment='平均分', decimal_places=2, max_digits=5, null=True)),
                ('std_dev', models.DecimalField(db_comment='标准差', decimal_places=2, max_digits=5, null=True)),
                ('max_score', models.DecimalField(db_comment='最高分', decimal_places=2, max_digits=5, null=True)),
                ('min_score', models.DecimalField(db_comment='最低分', decimal_places=2, max_digits=5, null=True)),
                ('pass_rate', models.DecimalField(db_comment='及格率', decimal_places=2, max_digits=5, null=True)),
                ('excellent_rate', models.DecimalField(db_comment='优秀率', decimal_places=2, max_digits=5, null=True)),
                ('low_score_rate', models.DecimalField(db_comment='低分率', decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(db_comment='状态：active/inactive', default='active', max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '考试科目配置',
                'verbose_name_plural': '考试科目配置',
                'db_table': 'exam_subject_config',
                'managed': False,
            },
        ),
    ]
