# Generated by Django 5.1.3 on 2024-12-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentIDMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('student_registration', models.CharField(help_text='全国统一学籍号', max_length=20, unique=True, verbose_name='学籍号')),
                ('id_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('primary_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='小学学号')),
                ('middle_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='初中学号')),
                ('high_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='高中学号')),
                ('current_level', models.CharField(choices=[('H', '高中'), ('M', '初中'), ('P', '小学')], max_length=1, verbose_name='当前学段')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生ID映射',
                'verbose_name_plural': '学生ID映射',
                'db_table': 'student_id_mapping',
                'indexes': [models.Index(fields=['student_registration'], name='student_id__student_238a8d_idx'), models.Index(fields=['id_number'], name='student_id__id_numb_fda2ec_idx'), models.Index(fields=['primary_id'], name='student_id__primary_470213_idx'), models.Index(fields=['middle_id'], name='student_id__middle__afe35d_idx'), models.Index(fields=['high_id'], name='student_id__high_id_76aa39_idx'), models.Index(fields=['student_name'], name='student_id__student_eee462_idx')],
            },
        ),
    ]
